### ISSUE TITLE
Release Checklist - v0.1

### ISSUE THREAD

**Issue by TonyGrif** [TonyGrif/billboard#1]
Tasks required for the next release

## Features
- [x] Scrape song data from the billboard hot 100
- [x] Scrape artist data from the billboard hot 100
- [x] Create methods to gather specific artists entries
- [x] Create method to gather the top spot

## Documentation
- [x] Update README project description
- [x] Update README project requirements
- [x] Update README example usage

## CI/CD
- [x] Automated testing via GitHub actions
- [x] Automated deployment on releases via GitHub actions (moved to #2)
