### ISSUE TITLE
Release Checklist - v0.4

### ISSUE THREAD

**Issue by TonyGrif** [TonyGrif/billboard#10]
Requirements for releasing the next release (0.4)

[Previous Release](https://github.com/TonyGrif/billboard/issues/3#issue-2514734004)

## Features
- [x] Album chart scraping

## Project
- [x] Automated posting to PyPi on tag

## Fixes
- [x] Pull utility functions into a standalone utilities module
