### ISSUE TITLE
Release Checklist - v0.2

### ISSUE THREAD

**Issue by TonyGrif** [TonyGrif/billboard#2]
Tasks required to release version 0.2

[Previous release](https://github.com/TonyGrif/billboard/issues/1#issue-2514426099 )

## Features
- [x] Scrape the billboard global 200 chart

## API
- [x] Create central class that will fetch multiple charts for a given week
- [x] Allow for the import of the monolithic class or individual charts

## Fixes
- [x] Remove use of exceptions in block parsing in favor of using None

## Documentation
- [x] Update chart entry documentation
- [x] Create documentation site from generator (moved to #3 )

## CI/CD
- [x] Automate wheel file creation on tag via GitHub actions
- [x] Automate publishing the created wheel file on release via GitHub actions
