### ISSUE TITLE
Release Checklist - v0.3

### ISSUE THREAD

**Issue by TonyGrif** [TonyGrif/billboard#3]
Tasks required for next release

[Previous release](https://github.com/TonyGrif/billboard/issues/2#issue-2514457867)

## Features
- [x] Scrape the Billboard 100 artist chart

## Fixes
- [x] Bump project version in pyproject

## Documentation
- [x] Create documentation site from generator
